apiVersion: batch/v1
kind: CronJob
metadata:
  name: deschedule-descheduler
  labels:
    app.kubernetes.io/name: descheduler
    app.kubernetes.io/instance: deschedule
spec:
  schedule: '*/2 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: deschedule-descheduler
          annotations:
            checksum/config: da31cf84a8a4417f138fe0417f5b6f7b89c8ff37b2d2910c42b7a4104782fbdd
          labels:
            app.kubernetes.io/name: descheduler
            app.kubernetes.io/instance: deschedule
        spec:
          priorityClassName: system-cluster-critical
          serviceAccountName: deschedule-descheduler
          restartPolicy: Never
          containers:
            - name: descheduler
              image: {{ kustom.image }}
              imagePullPolicy: IfNotPresent
              command:
                - /bin/descheduler
              args:
                - --policy-config-file=/policy-dir/policy.yaml
                - --v=3
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthz
                  port: 10258
                  scheme: HTTPS
                initialDelaySeconds: 5
                periodSeconds: 20
                timeoutSeconds: 5
              ports:
                - containerPort: 10258
                  protocol: TCP
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 500m
                  memory: 256Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                runAsUser: 1000
              volumeMounts:
                - mountPath: /policy-dir
                  name: policy-volume
          volumes:
            - name: policy-volume
              configMap:
                name: deschedule-descheduler
