apiVersion: v1
kind: ServiceAccount
metadata:
  name: deschedule-descheduler
  labels:
    app.kubernetes.io/name: descheduler
    app.kubernetes.io/instance: deschedule
    app.kubernetes.io/version: 0.33.0
