apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ kustom.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ kustom.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ kustom.name }}
    spec:
      containers:
      - args:
        - main:app
        - --host
        - 0.0.0.0
        - --port
        - "28381"
        - --reload
        command:
        - uvicorn
        env:
        - name: PYTHONPATH
          value: /app/backend/:/py_env/lib/python3.13/site-packages/
        image: {{ kustom.image }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /check
            port: infopage
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
        name: infopage
        ports:
        - containerPort: 28381
          name: infopage
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /check
            port: infopage
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 3
        volumeMounts:
        - mountPath: /app
          name: infopage
        workingDir: /app/backend
      serviceAccount: {{ kustom.name }}
      serviceAccountName: {{ kustom.name }}
      volumes:
      - name: infopage
        persistentVolumeClaim:
          claimName: infopage
