apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ kustom.name }}
  name: {{ kustom.name }}
spec:
  ports:
  - name: http
    port: 1111
    protocol: TCP
    targetPort: {{ kustom.name }}
  selector:
    app.kubernetes.io/name: {{ kustom.name }}
