apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ kustom.name }}-mutate
data:
  mutate: |
    deployment:
      standards:
        /spec/revisionHistoryLimit: 3
    pods:
        flannel:
            identifiedBy: label
            label: app
            exemptions:
            - hostPath
            - hostNetwork
            - readOnlyRootFilesystem
            - runAsNonRoot
            set:
              install-cni-plugin:
                uid: 0
                caps:
                - DAC_OVERRIDE
                - FOWNER
                - SYS_ADMIN
            install-cni:
                uid: 0
            kube-flannel:
                uid: 0
                caps:
                - DAC_OVERRIDE
                - FOWNER
                - SYS_ADMIN
                - NET_RAW
                - NET_ADMIN
        instance-manager:
            identifiedBy: label
            label: longhorn.io/component
            exemptions:
            - privileged
            - hostPath
            - runAsNonRoot
            - readOnlyRootFilesystem
            set:
              instance-manager:
                uid: 0
        engine-image:
            identifiedBy: label
            label: longhorn.io/component
            exemptions:
            - hostPath
            - runAsNonRoot
            - privileged
            set:
              engine-image-ei-62d76070:
                uid: 0
        csi-resizer:
            identifiedBy: label
            label: app
            exemptions:
            - hostPath
            - runAsNonRoot
            set:
              csi-resizer:
                uid: 0
        csi-snapshotter:
            identifiedBy: label
            label: app
            exemptions:
            - hostPath
            - runAsNonRoot
            set:
              csi-snapshotter:
                uid: 0
        csi-provisioner:
            identifiedBy: label
            label: app
            exemptions:
            - hostPath
            - runAsNonRoot
            set:
              csi-provisioner:
                uid: 0
        csi-attacher:
            identifiedBy: label
            label: app
            exemptions:
            - hostPath
            - runAsNonRoot
            set:
              csi-attacher:
                uid: 0
        longhorn-csi-plugin:
            identifiedBy: label
            label: app
            exemptions:
            - hostPath
            - privileged
            - caps_add
            - runAsNonRoot
            set:
              longhorn-csi-plugin:
                uid: 0
              longhorn-liveness-probe:
                uid: 0
        longhorn-manager:
            identifiedBy: label
            label: app
            exemptions:
            - hostPath
            - privileged
            - runAsNonRoot
            - readOnlyRootFilesystem
            set:
              longhorn-manager:
                uid: 0
        longhorn-ui:
            identifiedBy: label
            label: app
            exemptions:
            - caps_add
            emptyDir:
            - path: /var/log/nginx
              container: longhorn-ui
            - path: /var/lib/nginx
              container: longhorn-ui
            - path: /run
              container: istio-init
            set:
              istio-init:
                uid: 0
        longhorn-driver-deployer:
            label: app
            pod2container:
            runAsUser:
                - longhorn-driver-deployer
        discover-proc-kubelet-cmdline:
            identifiedBy: name
            exemptions:
            - privileged
        postgres:
            identifiedBy: label
            label: app
            exemptions:
            - privileged
            - readOnlyRootFilesystem
        mosquitto:
            identifiedBy: label
            label: app.kubernetes.io/name
            set:
              mosquitto:
                uid: 1883
        zigbee2mqtt:
            identifiedBy: label
            label: app.kubernetes.io/name
            exemptions:
            - hostPath
            - privileged
            - readOnlyRootFilesystem
            - runAsNonRoot
            xset:
              zigbee2mqtt:
                gid: 20
                caps:
                - CAP_AUDIT_READ
                - CAP_AUDIT_WRITE
                - CAP_BLOCK_SUSPEND
                - CAP_BPF
                - CAP_CHECKPOINT_RESTORE
                - CAP_CHOWN
                - CAP_DAC_OVERRIDE
                - CAP_DAC_READ_SEARCH
                - CAP_FOWNER
                - CAP_FSETID
                - CAP_IPC_LOCK
                - CAP_IPC_OWNER
                - CAP_KILL
                - CAP_LEASE
                - CAP_LINUX_IMMUTABLE
                - CAP_MAC_ADMIN
                - CAP_MAC_OVERRIDE
                - CAP_MKNOD
                - CAP_NET_ADMIN
                - CAP_NET_BIND_SERVICE
                - CAP_NET_BROADCAST
                - CAP_NET_RAW
                - CAP_PERFMON
                - CAP_SETFCAP
                - CAP_SETGID
                - CAP_SETPCAP
                - CAP_SETUID
                - CAP_SYSLOG
                - CAP_SYS_ADMIN
                - CAP_SYS_BOOT
                - CAP_SYS_CHROOT
                - CAP_SYS_MODULE
                - CAP_SYS_NICE
                - CAP_SYS_PACCT
                - CAP_SYS_PTRACE
                - CAP_SYS_RAWIO
                - CAP_SYS_RESOURCE
                - CAP_SYS_TIME
                - CAP_SYS_TTY_CONFIG
                - CAP_WAKE_ALARM
            set:
              zigbee2mqtt:
                gid: 20
                uid: 0
            caps:
                - CAP_SYS_RAWIO
                - CAP_SYS_ADMIN
            emptyDir:
            - path: /log
              container: zigbee2mqtt
        istiodxx:
            identifiedBy: label
            label: app
            set:
            discovery:
                caps:
                - CAP_NET_BIND_SERVICE
        ha-gw:
            identifiedBy: label
            label: app
            set:
            istio-proxy:
                caps:
                - NET_BIND_SERVICE
        gateway:
            identifiedBy: label
            label: app
            set:
            istio-proxy:
                caps:
                - NET_BIND_SERVICE
