apiVersion: apps/v1
kind: Deployment
metadata:
  name: valmut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valmut
  template:
    metadata:
      labels:
        app: valmut
      annotations:
        redeploy-timestamp: "{{ lookup('pipe', 'date +%s') }}"
    spec:
      containers:
      - name: valmut
        image: {{ kustom.image }}
        args:
        - valmut-webhook:app
        - --host
        - 0.0.0.0
        - --port
        - "{{ kustom.podPort }}"
        - --ssl-certfile
        - /certs/tls.crt
        - --ssl-keyfile
        - /certs/tls.key
        - --reload
        command:
        - uvicorn
        env:
        - name: PYTHONPATH
          value: /app/backend/:/py_env/lib/python3.13/site-packages/
        ports:
        - containerPort: {{ kustom.podPort }}
        volumeMounts:
        - mountPath: /app
          name: valmut
        - name: tls-certs-volume
          mountPath: /certs
          readOnly: true
        workingDir: /app/
      volumes:
      - name: valmut
        persistentVolumeClaim:
          claimName: valmut
      - name: tls-certs-volume
        secret:
          secretName: my-tls-secret
          defaultMode: 0400

