apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ kustom.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ kustom.name }}
  template:
    metadata:
      labels:
        app: {{ kustom.name }}
      annotations:
        redeploy-timestamp: "{{ lookup('pipe', 'date +%s') }}"
    spec:
      containers:
      - name: {{ kustom.name }}
        image: {{ kustom.image }}
        args:
        - valmut-webhook:app
        - --host
        - 0.0.0.0
        - --port
        - "{{ kustom.podPort }}"
        - --ssl-certfile
        - /certs/tls.crt
        - --ssl-keyfile
        - /certs/tls.key
        - --reload
        command:
        - uvicorn
        env:
        - name: PYTHONPATH
          value: /app/backend/:/py_env/lib/python3.13/site-packages/
        ports:
        - containerPort: {{ kustom.podPort }}
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /app
          name: {{ kustom.name }}
        - name: tls-certs-volume
          mountPath: /certs
          readOnly: true
        workingDir: /app/
      serviceAccountName: {{ kustom.name }}
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ kustom.name }}
        name: config
      - name: {{ kustom.name }}
        persistentVolumeClaim:
          claimName: {{ kustom.name }}
      - name: tls-certs-volume
        secret:
          secretName: my-tls-secret
          defaultMode: 0400


