apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: muthook
webhooks:
  - name: m.u.t.a.t.e
    clientConfig:
      service:
        namespace: kubext
        name: valmut
        path: "/mutate" # The path on your webhook server for mutation requests (matching @app.post("/mutate"))
        # This is where your CA certificate bundle goes.
        # It must be the base64-encoded CA certificate that signed the TLS certificate
        # used by your 'fastapi-webhook-service'.
        #
        # To get this, if you're using self-signed certs for testing (like in the previous steps):
        # cat cert.pem | base64 | tr -d '\n'
        #
        # For production, this usually comes from your Kubernetes CA, cert-manager, or similar.
      caBundle: |
        {{ caBundle | indent(width=8, first=False) }}
    rules:
      - operations: ["CREATE", "UPDATE"] # The operations this webhook applies to
        apiGroups: [""] # "" indicates core API group (e.g., Pods, Services, Deployments)
        apiVersions: ["v1"] # The API versions this webhook applies to
        resources: ["pods"] # The resources this webhook applies to (e.g., "pods", "deployments")
    failurePolicy: Ignore # How Kubernetes handles webhook failures:
                        # - Fail: Denies the request if the webhook fails or is unreachable (recommended for strict policies)
                        # - Ignore: Allows the request to proceed even if the webhook fails (useful for non-critical mutations/validations)
    sideEffects: None # Indicates that calling the webhook has no side effects on objects other than the AdmissionReview request.
                      # Use 'NoneOnDryRun' if it has no side effects on dry run operations.
    admissionReviewVersions: ["v1", "v1beta1"] # Supported AdmissionReview versions (v1 is preferred)
    timeoutSeconds: 5 # Maximum time in seconds to wait for the webhook to respond
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - kube-system
        - kubext
