apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: valhook
webhooks:
  - name: v.a.l.i.d.a.t.e
    clientConfig:
      service:
        namespace: kubext # The namespace where your FastAPI webhook service is running
        name: valmut # The name of the Kubernetes Service exposing your webhook
        path: "/validate" # The path on your webhook server for validation requests (matching @app.post("/validate"))
      caBundle: |
        {{ caBundle }}
    rules:
      - operations: ["CREATE", "UPDATE"] # The operations this webhook applies to
        apiGroups: [""] # "" indicates core API group (e.g., Pods, Services, Deployments)
        apiVersions: ["v1"] # The API versions this webhook applies to
        resources: ["pods"] # The resources this webhook applies to (e.g., "pods", "deployments")
    failurePolicy: Ignore # How Kubernetes handles webhook failures:
                        # - Fail: Denies the request if the webhook fails or is unreachable (recommended for strict policies)
                        # - Ignore: Allows the request to proceed even if the webhook fails (useful for non-critical validations)
    sideEffects: None # Indicates that calling the webhook has no side effects on objects other than the AdmissionReview request.
                      # Use 'NoneOnDryRun' if it has no side effects on dry run operations.
    admissionReviewVersions: ["v1", "v1beta1"] # Supported AdmissionReview versions (v1 is preferred)
    timeoutSeconds: 5 # Maximum time in seconds to wait for the webhook to respond
    # Optional: Further refine scope with namespaceSelector or objectSelector
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - kube-system
        - kubext
