apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  labels:
    app: postgres
data:
  postgresql.conf: listen_addresses='*'
  pg_hba.conf: |
    host    all             all             {{ kustom.trustedSubnet }}           trust
    host    all             all             127.0.0.1/32           trust
