apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ kustom.namespace }}
resources:
  - https://github.com/flannel-io/flannel/releases/download/{{ software.flannel.version }}/kube-flannel.yml

patches:
  - target:
      kind: DaemonSet
      name: kube-flannel-ds
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--iface=end0"
      - op: remove
        path: /spec/selector/matchLabels/k8s-app
      - op: remove
        path: /spec/template/metadata/labels/k8s-app
