namespace: {{ kustom.namespace }}
resources:
- Deployment.yaml
- HorizontalPodAutoscaler.yaml
- RoleBinding.yaml
- Role.yaml
- ServiceAccount.yaml
- Service.yaml
- gateway.yaml
  
secretGenerator:
- name: tls-{{ kustom.name }}
  files:
  - tls.crt=tls.crt
  - tls.key=tls.key
  type: "kubernetes.io/tls"
generatorOptions:
  disableNameSuffixHash: true


replacements:
  - source:
      kind: Secret
      name: tls-{{ kustom.name }}
      fieldPath: metadata.name     # We want the *generated name* of the Secret (with hash)
    targets:
      - select:
          kind: Gateway
          name: {{ kustom.name }}
        fieldPaths:
        - spec.servers.0.tls.credentialName

