apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ kustom.name }}
    istio: {{ kustom.name }}
  name: {{ kustom.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ kustom.name }}
subjects:
- kind: ServiceAccount
  name: {{ kustom.name }}
