apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ kustom.name }}
    istio: {{ kustom.name }}
  name: {{ kustom.name }}
spec:
  allocateLoadBalancerNodePorts: true
  externalIPs:
  - {{ kustom.network.endpointIP }}
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 33443
  selector:
    app: {{ kustom.name }}
    istio: {{ kustom.name }}
  sessionAffinity: None
  type: LoadBalancer
