apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ kustom.name }}
    istio: {{ kustom.name }}
  name: {{ kustom.name }}
spec:
  externalIPs:
  - {{ (net.routes | selectattr('domain','equalto',kustom.network.domain)|first).endpointIP }}
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 33443
  selector:
    app: {{ kustom.name }}
    istio: {{ kustom.name }}
  type: LoadBalancer
