apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ kustom.name }}
  name: {{ kustom.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ kustom.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ kustom.name }}
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --alpha-config=/etc/oauth2_proxy_alpha/oauth2_proxy.yml
        - --auth-logging=true
        - --cookie-expire=12h
        - --cookie-samesite=lax
        - --request-logging=true
        - --show-debug-on-error=true
        - --silence-ping-logging=true
        - --skip-provider-button=true
        - --standard-logging=true
        - --config=/etc/oauth2_proxy/oauth2_proxy.cfg
        image: {{ kustom.image }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          name: http
          protocol: TCP
        - containerPort: 44180
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /etc/oauth2_proxy
          name: configmain
        - mountPath: /etc/oauth2_proxy_alpha
          name: configalpha
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: oauth2_proxy.cfg
            path: oauth2_proxy.cfg
          name: oauth2-proxy
        name: configmain
      - name: configalpha
        secret:
          defaultMode: 420
          items:
          - key: oauth2_proxy.yml
            path: oauth2_proxy.yml
          secretName: oauth2-proxy-alpha
