apiVersion: v1
type: Opaque
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: oauth2-proxy
  name: oauth2-proxy-alpha
stringData:
  oauth2_proxy.yml: |
       server:
         BindAddress: "0.0.0.0:4180"
       providers:
       - clientID: "{{ auth.client_id }}"
         clientSecret: "{{ auth.client_secret }}" # IdP Client Secret
         id: oidc-istio
         provider: oidc   # We use the generic 'oidc' provider
         profileURL: http://hydra-public.auth:4444/userinfo
         scope: "email openid"
         # scope: "openid email profile groups"
         #allowedGroups:
         #- admins # List all groups managed at our your IdP which should be allowed access
         oidcConfig:
          userIDClaim: sub  # Name of the claim in JWT containing the User ID
          emailClaim: sub
          audienceClaims:
          - aud
          issuerURL: https://{{ net.base_domain }}/hydra
          jwksURL: http://hydra.auth:1121/
       upstreamConfig:
          upstreams:
          - id: static_200
            path: /
            static: true
            staticCode: 200

