apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ kustom.name }}
    app.kubernetes.io/name: {{ kustom.name }}
  name: {{ kustom.name }}
spec:
  ports:
  - appProtocol: http
    name: http
    port: {{ kustom.network.svcPort }}
    protocol: TCP
    targetPort: http
  - appProtocol: http
    name: metrics
    port: 44180
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: {{ kustom.name }}
  type: ClusterIP
