apiVersion: v1
kind: Secret
metadata:
  name: hydra
  labels:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/instance: hydra
type: Opaque
data:
  secretsSystem: TEtKRkQpKWhmaE9JSlNERklo
  secretsCookie: TEtKRkQpKWhmaE9JSlNERklo
  dsn: bWVtb3J5
