apiVersion: v1
kind: Service
metadata:
  name: hydra-public
  labels:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/instance: hydra
spec:
  type: ClusterIP
  ports:
    - port: 4444
      targetPort: http-public
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/instance: hydra
