apiVersion: v1
kind: ServiceAccount
metadata:
  name: hydra
  labels:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/instance: hydra
    app.kubernetes.io/version: v25.4.0
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: hydra-0.60.0
automountServiceAccountToken: false
