apiVersion: v1
kind: Service
metadata:
  name: hydra-admin
  labels:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/instance: hydra
    app.kubernetes.io/version: v25.4.0
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: hydra-0.60.0
    app.kubernetes.io/component: admin
  annotations: null
spec:
  type: ClusterIP
  ports:
    - port: 4445
      targetPort: http-admin
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hydra
    app.kubernetes.io/instance: hydra
