apiVersion: v1
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    listener 1883
    socket_domain ipv4
    log_type all
    listener 9090
    socket_domain ipv4
    log_type all
    protocol websockets

    password_file /mosquitto/data/mosquitto.passwd
kind: ConfigMap
metadata:
  name: mosquitto
