apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local
  volumeMode: Filesystem
  volumeName: mosquitto
