apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: {{ kustom.name }}
    app.kubernetes.io/name: {{ kustom.name }}
  name: {{ kustom.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ kustom.name }}
      app.kubernetes.io/name: {{ kustom.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ kustom.name }}
        app.kubernetes.io/name: {{ kustom.name }}
        app: {{ kustom.name }}
    spec:
      containers:
      - image: {{ kustom.image }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 1
          tcpSocket:
            port: websocket
        name: {{ kustom.name }}
        securityContext:
          runAsUser: {{ kustom.security.runAsUser }}
        ports:
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        - containerPort: 9090
          name: websocket
          protocol: TCP
        readinessProbe:
          initialDelaySeconds: 3
          periodSeconds: 3
          tcpSocket:
            port: websocket
        volumeMounts:
        - mountPath: /{{ kustom.name }}/config
          name: config
        - mountPath: /{{ kustom.name }}/data
          name: data
      restartPolicy: Always
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: {{ kustom.name }}
          - secret:
              name: {{ kustom.name }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: {{ kustom.storage[0].type }}
      resources:
        requests:
          storage: {{ kustom.storage[0].size }}
