# kustomize/base/traefik-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: {{ kustom.image }}
          command: ['/bin/traefik']
          args:
            - "--api.dashboard=true"
            - --ping=true
            - --ping.entrypoint=traefik
            - "--providers.kubernetesingress"
            - "--providers.kubernetesingress.ingressclass=traefik"
            - "--providers.kubernetesingress.labelselector=app=my-app-ingress"
            - "--providers.kubernetescrd"
            - "--entrypoints.web.address=:9980"
            - "--entrypoints.websecure.address=:9443"
            - "--entrypoints.traefik.address=:{{ kustom.ports.traefik }}"
            - "--log.level=DEBUG"
          ports:
            - name: web
              containerPort: 9980
            - name: websecure
              containerPort: 9443
            - name: traefik
              containerPort: {{ kustom.ports.traefik }}
            - name: metrics
              containerPort: 8082 # For Prometheus metrics
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ kustom.ports.traefik }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ kustom.ports.traefik }}

