apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ kustom.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  volumeName: {{ kustom.name }}
