apiVersion: v1
kind: Service
metadata:
  name: {{ kustom.name }}
spec:
  ports:
    - name: http
      port: {{ kustom.network.svcPort }}
      targetPort: 8123
    - name: metrics
      port: 9090
      targetPort: 9090

