apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ kustom.name }}
roleRef:
  kind: ClusterRole
  name: {{ kustom.name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ kustom.name }}
    namespace: {{ kustom.namespace }}

