apiVersion: v1
kind: Service
metadata:
  name: idp
spec:
  ports:
  - name: http
    port: {{ kustom.network.svcPort }}
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: idp
