apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ kustom.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: zigbee2mqtt
      app.kubernetes.io/name: zigbee2mqtt

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: zigbee2mqtt
        app.kubernetes.io/name: zigbee2mqtt
    spec:
      containers:
      - args:
        - sleep 20; /z/initconfig.sh
        command:
        - /bin/sh
        - -c
        image: {{ kustom.image }}
        imagePullPolicy: IfNotPresent
        name: {{ kustom.name }}
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
          readOnlyRootFilesystem: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/data
          name: zigbee2mqtt-data
        - mountPath: /z
          name: zigbee2mqtt-config
        - mountPath: /dev/ttyUSB0
          name: zigbeedongle
      nodeSelector:
        zigbee2mqtt: zigbee2mqtt
      volumes:
      - configMap:
          defaultMode: 493
          items:
          - key: initconfig.sh
            mode: 511
            path: initconfig.sh
          name: zigbee2mqtt
        name: zigbee2mqtt-config
      - name: zigbee2mqtt-data
        persistentVolumeClaim:
          claimName: zigbee2mqtt
      - hostPath:
          path: /dev/ttyUSB0
          type: CharDevice
        name: zigbeedongle
