namespace: {{ kustom.namespace }}
resources:
  - statefulset.yaml
  - service.yaml
  - persistentvolumeclaim.yaml

configMapGenerator:
  - name: {{ kustom.name }}
    files:
      - configuration.yaml

