apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ kustom.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ kustom.storage[0].size }}
  storageClassName: local
  volumeMode: Filesystem
  volumeName: {{ kustom.name }}
