{% raw %}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istiod-gateway-controller-istio-system
  labels:
    app: istiod
    release: istiod
    app.kubernetes.io/name: istiod
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.0.0
rules:
  - apiGroups:
      - apps
    verbs:
      - get
      - watch
      - list
      - update
      - patch
      - create
      - delete
    resources:
      - deployments
  - apiGroups:
      - ''
    verbs:
      - get
      - watch
      - list
      - update
      - patch
      - create
      - delete
    resources:
      - services
  - apiGroups:
      - ''
    verbs:
      - get
      - watch
      - list
      - update
      - patch
      - create
      - delete
    resources:
      - serviceaccounts
{% endraw %}
