{% raw %}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-reader-clusterrole-istio-system
  labels:
    app: istio-reader
    release: istiod
    app.kubernetes.io/name: istio-reader
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.0.0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-reader-clusterrole-istio-system
subjects:
  - kind: ServiceAccount
    name: istio-reader-service-account
    namespace: istio-system
{% endraw %}
