{% raw %}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istiod
  labels:
    app: istiod
    release: istiod
    app.kubernetes.io/name: istiod
    app.kubernetes.io/instance: istiod
    app.kubernetes.io/part-of: istio
    app.kubernetes.io/version: 1.0.0
rules:
  - apiGroups:
      - networking.istio.io
    verbs:
      - create
    resources:
      - gateways
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
      - get
      - watch
      - list
      - update
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - update
      - patch
      - create
{% endraw %}
